public class Constants {
    
    public static final Set<String> ARIFMETIC_OPERATORS_CONST = new Set<String>{'<','>','<=','>=','='};
    public static final List<String> ALL_PRODUCT2_FIELDS_CONST = new List<String>{'Id','Name','BataryCapacity__c','Catigory__c','ChargingTime__c','Color__c','MaxSpeed__c','MaxWeight__c','TravelDistance__c','(SELECT UnitPrice FROM PricebookEntries)'   };
    public static final String CURRENT_PRICEBOOK_ID_CONST = '01s2v00000NO9hKAAT';
}
